### ISSUE TITLE
Research bug with BetterStorage

### ISSUE THREAD

**Issue by DonDanko** [DigglesMods/BetterStorage#7]
Hi, 

i found a bug, when i have BetterStorage aktivated and i want to research the club or the bar. They will not really get researcht. The Diggles go there and do the animation, and in the newsticker there will be a message. But in the Building i can/musst still research it. And cannot build it because of that. If i deactivate the Mod the reseach of these two will work without problems.

Also when i build the Kitchen, i have to research all the Foods (even the Fungus and Hamster one) and the also cannot be researched as with the club or the bar. But im not sure if that is related, because if i deactivate the Mod i still have the same problem with the kitchen.

**Comment by cech12** [comment]
Unfortunately this mod does not work with savegames. Starting a new game or uninstalling this mod should fix this bug.

**Comment by zbanan003** [comment]
> Unfortunately this mod does not work with savegames. Starting a new game or uninstalling this mod should fix this bug.

Could you please add this information somewhere on top of mod description? Or in the tooltip in the mod manager? I also tried this mod on existing save and all my dwarves got immediately age 29 and strated dying :(

**Comment by cech12** [comment]
yep

**Comment by cech12** [comment]
This bug cannot be fixed until someone find a solution to change the savegames in such a way that the saved techtree is compatible with the modded techtree.
I added a link to the download page: https://digglesmods.github.io/DigglesModManager/

In the future I will add such a hint to the DigglesModManager itself: https://github.com/DigglesMods/DigglesModManager/issues/34
