### ISSUE TITLE
Taucherglocke & Schubkarren

### ISSUE THREAD

**Issue by cech12** [DigglesMods/BetterStorage#9]
These two items are not stored when tools storing is enabled

Check if Presslufthammer & Kristallstrahl are working correctly.

**Comment by Chris1231** [comment]
Hast du in der lager.tcl unter "liefert Klassennamen zum Einlagen"  bei if {$store_misc} die items eingetragen?

**Comment by cech12** [comment]
Bisher nicht^^ Deshalb ja das Ticket hier^^

https://github.com/DigglesMods/BetterStorage/blob/6f850e8b57eb23b3bfe5071e7e5640211eda44b1/Data/Scripts/classes/work/change_lager.tcl#L256

**Comment by cech12** [comment]
Presslufthammer & Kristallstrahl are working correctly
